version: "3"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=medium
    ports:
      - 3306:3306

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: arkisoul/drf:latest
    container_name: drf
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app
    environment:
      - DJANGO_SECRET_KEY=secret_key
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medium
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  # worker:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: arkisoul/drf:latest
  #   container_name: celery_worker
  #   command: celery -A todo_app._celery:_celery worker -l INFO
  #   environment:
  #     - DJANGO_SECRET_KEY=secret_key
  #     - MYSQL_HOST=mysql
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=todos
  #     - REDIS_HOST=redis
  #     - PYTHONUNBUFFERED=1
  #   volumes:
  #     - ./src:/usr/src/app
  #   depends_on:
  #     - mysql
  #     - redis

  # clock:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: arkisoul/drf:latest
  #   container_name: celery_clock
  #   command: celery -A todo_app._celery:_celery beat -l INFO
  #   volumes:
  #     - ./src:/usr/src/app
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DJANGO_SECRET_KEY=secret_key
  #     - MYSQL_HOST=mysql
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=todos
  #     - REDIS_HOST=redis
  #   depends_on:
  #     - mysql
  #     - redis

  # haproxy:
  #   image: dockercloud/haproxy
  #   ports:
  #     - 80:80
  #   links:
  #     - web
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
